### ISSUE TITLE
Outlook Desktop Version Report Problem

### ISSUE THREAD

**Issue by sefnix** [dwtechnologies/gophish-owa-phishing-reporter#3]
Hi, the reporting section does not work in the outlook desktop version of the application. Do you have an idea about this ? 
Thanks for your understanding.
![reporter_problem](https://user-images.githubusercontent.com/54702941/205625889-1744c839-c454-4447-a58e-e45a346e5dc1.png)

**Comment by lerra** [comment]
Hi,

Sorry but I dont understand the language in the error, I would recommend you to go through the instructions again and customize it to your setup. I can see that you have not changed the URL and hosting the static files your self with your settings.
